version: "3.8"

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - JWT_TOKEN=${JWT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: expense_tracker
      POSTGRES_PASSWORD: 99556688
      POSTGRES_DB: expense_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  seed:
    build: .
    command: npm run seed
    depends_on:
      - db

volumes:
  postgres-data:
